### ISSUE TITLE
Possible false positive during luacheck.

### ISSUE THREAD

**Issue by nicolas-lang** [Nexela/Factorio-luacheckrc#23]
#### Describe the Bug

Since the last update the luacheck seems to require "util" to be pre-registered when it is used.
As far as I know, util is auto loaded in data stage by the factorio engine, even though I have failed to find this "in writing" ( the closest mention is https://forums.factorio.com/viewtopic.php?t=32761 )

![image](https://user-images.githubusercontent.com/635895/159979468-19db3afb-5b3f-443f-abd6-26a5ee2bc6af.png)

The issue persists even with a `require("util")`

#### To Reproduce

![image](https://user-images.githubusercontent.com/635895/159979620-18119751-53fb-4da3-8c4d-4afdfced334f.png)
see https://github.com/ILLISIS/Constructron-Continued/blob/main/data/service_station.lua

**Comment by Nexela** [comment]
Hmmmm, I think I need to setup an action to luacheck the .luacheckrc looks like I shadowed the util definition.

> As far as I know, util is auto loaded in data stage by the factorio engine, even though I have failed to find this "in writing" 

Since the data stage is shared between all mods whenever a mod `requires 'util'` the `util` global is created. So when base or core `requires 'util'` it's available for all mods that load after.  Since there is no gurantee that util will be available at any given time it doesn't hurt to `require` it into your mod, even better require it locally  `local util = require('util')`
